#!/usr/bin/env node
// Render spec/model.mjs into a TLA+ module.
//
// Concord.tla is generated, never hand-edited, for the reason the exhaustive
// checker's header gives: a model in a second notation is a second artefact
// that can drift from the code. This one cannot drift, because it is produced
// from the same objects spec/check.mjs executes, and spec/model.test.mjs fails
// if the committed file is not what this produces.
//
//   node spec/build.mjs
//
// What that guarantees is that every action and invariant in the model appears
// in the module, under the same name, in the same order. What it cannot
// guarantee is that the TLA+ text of an action means the same thing as its
// JavaScript -- those are written side by side by a person. The authority in
// this repository is check.mjs; the module is for anyone who wants to put the
// same machine through TLC.

import { writeFile } from 'node:fs/promises';
import { ACTIONS, INVARIANTS } from './model.mjs';

// Rendering and writing are separate on purpose. The test that checks the
// committed module is current used to run this file, which meant it repaired
// what it was checking: a stale artefact failed once and passed for ever after,
// which is the failure mode of a check nobody can trust. It compares render()
// against the file now, and writes nothing.

const HEADER = `---------------------------- MODULE Concord ----------------------------
(***************************************************************************)
(* The Concord commitment protocol.                                        *)
(*                                                                         *)
(* GENERATED by spec/build.mjs from spec/model.mjs. Do not edit: the same   *)
(* actions and invariants are executed exhaustively by spec/check.mjs on    *)
(* every test run, and a test fails if this file is not what the generator  *)
(* produces.                                                               *)
(*                                                                         *)
(* Concord's claim is that an agent cannot promise what a set of websites   *)
(* cannot deliver, and that the tool which carries out a commitment does    *)
(* not exist until a person has accepted the guarantee they were shown.     *)
(* Both are safety properties, and both are below.                          *)
(***************************************************************************)
EXTENDS Naturals, FiniteSets, Sequences

CONSTANTS Vendors,          \\* the participants in this commitment
          Rung              \\* [Vendors -> {"reservable", "compensable", "irreversible"}]

VARIABLES proposed,         \\* a plan has been computed
          committable,      \\* that plan admits an honest guarantee
          explained,        \\* the guarantee has been read out
          accepted,         \\* a person accepted it, on the page
          spent,            \\* that acceptance has been used to start a commitment
          phase,            \\* idle -> reserve -> execute -> irreversible -> confirm -> settled
          journalled,       \\* steps whose intent is durably recorded
          performed,        \\* steps whose effect actually happened
          reversed,         \\* steps that have been taken back
          outcome

vars == << proposed, committable, explained, accepted, spent, phase,
           journalled, performed, reversed, outcome >>

Phases == << "idle", "reserve", "execute", "irreversible", "confirm", "settled" >>

Irreversible == { v \\in Vendors : Rung[v] = "irreversible" }
Reversible   == { v \\in Vendors : Rung[v] # "irreversible" }

StepOf(v) == IF Rung[v] = "reservable" THEN "reserve" ELSE "execute"

IsIrreversible(k) == \\E v \\in Irreversible : k = << v, StepOf(v) >>

\\* Which rung acts in the phase the machine is currently in.
ActsNow(v) ==
  \\/ (phase = "reserve"      /\\ Rung[v] = "reservable")
  \\/ (phase = "execute"      /\\ Rung[v] = "compensable")
  \\/ (phase = "irreversible" /\\ Rung[v] = "irreversible")

ActsOn(v, st) == ActsNow(v) /\\ st = StepOf(v)

PhaseComplete == \\A v \\in Vendors : ActsNow(v) => << v, StepOf(v) >> \\in performed

NextPhase(p) == Phases[(CHOOSE i \\in 1..Len(Phases) : Phases[i] = p) + 1]

Steps == {"reserve", "execute"}

\\* The whole permission model, in one line. concord_commit is not disabled
\\* when this is false -- it is not registered at all.
CommitRegistered == accepted /\\ ~spent /\\ committable

Init ==
  /\\ proposed = FALSE
  /\\ committable = FALSE
  /\\ explained = FALSE
  /\\ accepted = FALSE
  /\\ spent = FALSE
  /\\ phase = "idle"
  /\\ journalled = {}
  /\\ performed = {}
  /\\ reversed = {}
  /\\ outcome = "none"
`;

const section = (title) => `
(* ---------------------------- ${title} ---------------------------- *)
`;

export function render() {
  const body = [
    HEADER,
    section('actions'),
    ...ACTIONS.map((a) => `${a.tla.join('\n')}\n`),
    `Step ==\n${ACTIONS.map((a) => (a.params
      ? `  \\/ \\E ${a.params[0]} \\in Vendors, ${a.params[1]} \\in Steps : ${a.name}(${a.params.join(', ')})`
      : `  \\/ ${a.name}`)).join('\n')}\n`,
    `Spec == Init /\\ [][Step]_vars\n`,
    section('safety'),
    ...INVARIANTS.map((i) => `\\* ${i.doc}\n${i.tla}\n`),
    `Safety ==\n${INVARIANTS.map((i) => `  /\\ ${i.name}`).join('\n')}\n`,
    `=============================================================================\n`,
  ].join('\n');

  const cfg = `\\* GENERATED by spec/build.mjs. Do not edit.
\\* Three participants, one of each rung, which is the shape spec/check.mjs
\\* enumerates exhaustively.
CONSTANTS
  Vendors = {v1, v2, v3}
  Rung = [v1 |-> "reservable", v2 |-> "compensable", v3 |-> "irreversible"]

INIT Init
NEXT Step

${INVARIANTS.map((i) => `INVARIANT ${i.name}`).join('\n')}
`;
  return { tla: body, cfg };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { tla, cfg } = render();
  await writeFile(new URL('./Concord.tla', import.meta.url), tla);
  await writeFile(new URL('./Concord.cfg', import.meta.url), cfg);
  console.log('  spec/Concord.tla');
  console.log('  spec/Concord.cfg');
}
