---------------------------- MODULE Concord ----------------------------
(***************************************************************************)
(* The Concord commitment protocol.                                        *)
(*                                                                         *)
(* GENERATED by spec/build.mjs from spec/model.mjs. Do not edit: the same   *)
(* actions and invariants are executed exhaustively by spec/check.mjs on    *)
(* every test run, and a test fails if this file is not what the generator  *)
(* produces.                                                               *)
(*                                                                         *)
(* Concord's claim is that an agent cannot promise what a set of websites   *)
(* cannot deliver, and that the tool which carries out a commitment does    *)
(* not exist until a person has accepted the guarantee they were shown.     *)
(* Both are safety properties, and both are below.                          *)
(***************************************************************************)
EXTENDS Naturals, FiniteSets, Sequences

CONSTANTS Vendors,          \* the participants in this commitment
          Rung              \* [Vendors -> {"reservable", "compensable", "irreversible"}]

VARIABLES proposed,         \* a plan has been computed
          committable,      \* that plan admits an honest guarantee
          explained,        \* the guarantee has been read out
          accepted,         \* a person accepted it, on the page
          spent,            \* that acceptance has been used to start a commitment
          phase,            \* idle -> reserve -> execute -> irreversible -> confirm -> settled
          journalled,       \* steps whose intent is durably recorded
          performed,        \* steps whose effect actually happened
          reversed,         \* steps that have been taken back
          outcome

vars == << proposed, committable, explained, accepted, spent, phase,
           journalled, performed, reversed, outcome >>

Phases == << "idle", "reserve", "execute", "irreversible", "confirm", "settled" >>

Irreversible == { v \in Vendors : Rung[v] = "irreversible" }
Reversible   == { v \in Vendors : Rung[v] # "irreversible" }

StepOf(v) == IF Rung[v] = "reservable" THEN "reserve" ELSE "execute"

IsIrreversible(k) == \E v \in Irreversible : k = << v, StepOf(v) >>

\* Which rung acts in the phase the machine is currently in.
ActsNow(v) ==
  \/ (phase = "reserve"      /\ Rung[v] = "reservable")
  \/ (phase = "execute"      /\ Rung[v] = "compensable")
  \/ (phase = "irreversible" /\ Rung[v] = "irreversible")

ActsOn(v, st) == ActsNow(v) /\ st = StepOf(v)

PhaseComplete == \A v \in Vendors : ActsNow(v) => << v, StepOf(v) >> \in performed

NextPhase(p) == Phases[(CHOOSE i \in 1..Len(Phases) : Phases[i] = p) + 1]

Steps == {"reserve", "execute"}

\* The whole permission model, in one line. concord_commit is not disabled
\* when this is false -- it is not registered at all.
CommitRegistered == accepted /\ ~spent /\ committable

Init ==
  /\ proposed = FALSE
  /\ committable = FALSE
  /\ explained = FALSE
  /\ accepted = FALSE
  /\ spent = FALSE
  /\ phase = "idle"
  /\ journalled = {}
  /\ performed = {}
  /\ reversed = {}
  /\ outcome = "none"


(* ---------------------------- actions ---------------------------- *)

Propose ==
  /\ ~spent /\ phase = "idle"
  /\ proposed' = TRUE
  /\ explained' = FALSE
  /\ accepted' = FALSE
  /\ committable' = (Cardinality(Irreversible) <= 1)
  /\ UNCHANGED << spent, phase, journalled, performed, reversed, outcome >>

Explain ==
  /\ proposed /\ phase = "idle"
  /\ explained' = TRUE
  /\ UNCHANGED << proposed, committable, accepted, spent, phase,
                  journalled, performed, reversed, outcome >>

Accept ==
  /\ proposed /\ explained /\ committable /\ ~accepted /\ phase = "idle"
  /\ accepted' = TRUE
  /\ UNCHANGED << proposed, committable, explained, spent, phase,
                  journalled, performed, reversed, outcome >>

Repropose ==
  /\ proposed /\ phase = "idle"
  /\ explained' = FALSE
  /\ accepted' = FALSE
  /\ UNCHANGED << proposed, committable, spent, phase,
                  journalled, performed, reversed, outcome >>

BeginCommitment ==
  /\ accepted /\ ~spent /\ committable /\ phase = "idle"
  /\ spent' = TRUE
  /\ phase' = "reserve"
  /\ UNCHANGED << proposed, committable, explained, accepted,
                  journalled, performed, reversed, outcome >>

JournalIntent(v, st) ==
  /\ phase \notin {"idle", "settled"}
  /\ ActsOn(v, st)
  /\ journalled' = journalled \cup {<<v, st>>}
  /\ UNCHANGED << proposed, committable, explained, accepted, spent,
                  phase, performed, reversed, outcome >>

Perform(v, st) ==
  /\ phase \notin {"idle", "settled"}
  /\ ActsOn(v, st)
  /\ <<v, st>> \in journalled
  /\ performed' = performed \cup {<<v, st>>}
  /\ UNCHANGED << proposed, committable, explained, accepted, spent,
                  phase, journalled, reversed, outcome >>

AdvancePhase ==
  /\ phase \notin {"idle", "settled"}
  /\ PhaseComplete
  /\ phase' = NextPhase(phase)
  /\ UNCHANGED << proposed, committable, explained, accepted, spent,
                  journalled, performed, reversed, outcome >>

Unwind ==
  /\ phase \in {"reserve", "execute"}
  /\ outcome = "none"
  /\ reversed' = { k \in performed : ~IsIrreversible(k) }
  /\ phase' = "settled"
  /\ outcome' = "unwound"
  /\ UNCHANGED << proposed, committable, explained, accepted, spent,
                  journalled, performed >>

Settle ==
  /\ phase = "confirm" /\ PhaseComplete /\ outcome = "none"
  /\ phase' = "settled"
  /\ outcome' = "committed"
  /\ UNCHANGED << proposed, committable, explained, accepted, spent,
                  journalled, performed, reversed >>

Refuse ==
  /\ proposed /\ ~committable /\ phase = "idle" /\ outcome = "none"
  /\ phase' = "settled"
  /\ outcome' = "refused"
  /\ UNCHANGED << proposed, committable, explained, accepted, spent,
                  journalled, performed, reversed >>

Step ==
  \/ Propose
  \/ Explain
  \/ Accept
  \/ Repropose
  \/ BeginCommitment
  \/ \E v \in Vendors, st \in Steps : JournalIntent(v, st)
  \/ \E v \in Vendors, st \in Steps : Perform(v, st)
  \/ AdvancePhase
  \/ Unwind
  \/ Settle
  \/ Refuse

Spec == Init /\ [][Step]_vars


(* ---------------------------- safety ---------------------------- *)

\* nothing is ever contacted unless a person accepted a guarantee first
NoEffectWithoutAcceptance == (performed # {}) => (accepted /\ spent)

\* a plan with no honest guarantee can never be accepted
NoAcceptanceOfRefused == accepted => committable

\* no effect happens whose intent was not written down first
JournalBeforeEffect == performed \subseteq journalled

\* nothing irreversible is touched while anything reversible is unsettled
IrreversibleIsLast ==
  (\E k \in performed : IsIrreversible(k))
    => (\A p \in Reversible : <<p, StepOf(p)>> \in performed)

\* a committable plan never contains two things that cannot be taken back
AtMostOneIrreversible == committable => Cardinality(Irreversible) <= 1

\* "this did not happen" is never said after something that cannot be undone
UnwoundMeansNothingIrreversibleRan ==
  (outcome = "unwound") => ~(\E k \in performed : IsIrreversible(k))

\* an unwound commitment left nothing standing
UnwoundMeansEverythingReversed == (outcome = "unwound") => performed \subseteq reversed

\* the commit tool is registered exactly when a person has accepted and not yet spent it
CommitToolIffUnspentAcceptance ==
  CommitRegistered <=> (accepted /\ ~spent /\ committable)

\* a refusal is computed before contact, so a refused commitment contacted nobody
RefusedTouchesNothing == (outcome = "refused") => performed = {}

Safety ==
  /\ NoEffectWithoutAcceptance
  /\ NoAcceptanceOfRefused
  /\ JournalBeforeEffect
  /\ IrreversibleIsLast
  /\ AtMostOneIrreversible
  /\ UnwoundMeansNothingIrreversibleRan
  /\ UnwoundMeansEverythingReversed
  /\ CommitToolIffUnspentAcceptance
  /\ RefusedTouchesNothing

=============================================================================
