#!/usr/bin/env bash
# Write down what actually happened, so the claims can be checked cold.
#
# Every number in the README comes from one of these runs. They are committed
# rather than described, because "121 assertions" and "all fourteen attacks
# rejected" are things a reader should be able to see the output of without
# installing anything -- and because a claim that is regenerated by a script is
# a claim that gets caught when it stops being true.
#
# mutation.txt is not regenerated here: a full run is over an hour, and a file
# that is silently a month old is worse than one whose age is on its face. Run
# `npm run mutants > evidence/mutation.txt` deliberately.
#
#   npm run evidence
set -uo pipefail
cd "$(dirname "$0")/.."
mkdir -p evidence
stamp() { printf '# %s\n# generated by tools/evidence.sh — do not edit\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"; }

echo "  evidence/tests.txt"
{ stamp; npm test 2>&1 | tail -40; } > evidence/tests.txt

echo "  evidence/model.txt"
{ stamp
  echo "the commitment protocol, model-checked over every reachable state:"
  echo
  node spec/check.mjs 2>&1
} > evidence/model.txt

echo "  evidence/attacks.txt"
{ stamp; VERBOSE=1 node attacks/run.mjs 2>&1; } > evidence/attacks.txt

echo "  evidence/live.txt"
{ stamp; node deploy/verify-live.mjs 2>&1; } > evidence/live.txt

echo "  evidence/surface.txt"
{ stamp
  echo "against the live deployment:"
  URL=https://concord-coordinator.vercel.app/ node evals/surface.mjs 2>&1
} > evidence/surface.txt

echo "  evidence/README.md"
cat > evidence/README.md <<'MD'
# Evidence

Output from real runs, committed so the claims in the README can be checked
without installing anything. Regenerate with `npm run evidence`.

| File | What it is |
|---|---|
| `tests.txt` | the protocol suite, no browser |
| `attacks.txt` | every forged receipt, and what the verifier objected to |
| `surface.txt` | the tool surface asserted state by state, against the live deployment |
| `live.txt` | every deployed origin checked from outside |
| `model.txt` | every safety invariant, over every reachable state of the protocol |
| `mutation.txt` | how many deliberate defects the suite catches — every mutant, not a sample |

None of this is a substitute for running it yourself. `npm run check` does all
of it at once, and `tools/check.sh` is forty lines you can read first.
MD
echo "  done"
